# Generated by Django 2.0.5 on 2018-05-13 13:09

from django.db import migrations
import simditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=simditor.fields.RichTextField(verbose_name='正文'),
        ),
    ]
